name: Deploy to AKS   # Pipeline ka naam

on:
  push:
    branches:
      - main         # Jab bhi main branch me code push hoga

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   # GitHub ka runner (Linux VM)

    steps:

    - name: Checkout code
      uses: actions/checkout@v3   # Repo ka code pipeline me lana

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}   # Secure login

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: rg-aks-demo
        cluster-name: aks-demo

    - name: Deploy to AKS
      run: kubectl apply -f deployment.yaml